'use strict';
const $=id=>document.getElementById(id),canvas=$('gameCanvas'),ctx=canvas.getContext('2d'),TAU=Math.PI*2;
const ui={level:$('levelValue'),wave:$('waveValue'),kills:$('killsValue'),time:$('timeValue'),health:$('healthValue'),healthBar:$('healthBar'),xp:$('xpValue'),xpBar:$('xpBar'),slots:$('powerSlots'),slotCounter:$('slotCounter'),start:$('startModal'),levelModal:$('levelModal'),over:$('gameOverModal'),choices:$('powerChoices'),reroll:$('rerollButton'),rerolls:$('rerollsValue'),results:$('results'),announce:$('announcement'),pause:$('pauseButton')};
const keys=new Set(),rnd=(a,b)=>Math.random()*(b-a)+a,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),ang=(a,b)=>Math.atan2(b.y-a.y,b.x-a.x);
const POWERS=[
{id:'blaster',icon:'💥',name:'Tavi Blaster',desc:'Automatically fires at the nearest enemy.',up:l=>`Faster shots and ${10+l*4} damage.`,max:8},
{id:'orbit',icon:'🌀',name:'Orbiting Pints',desc:'Pints circle Tavi and batter nearby enemies.',up:l=>`${Math.min(6,l+1)} stronger orbiting pints.`,max:6},
{id:'lightning',icon:'⚡',name:'Chain Lightning',desc:'Lightning jumps through groups of enemies.',up:l=>`More damage and up to ${Math.min(6,l+2)} targets.`,max:7},
{id:'frost',icon:'❄️',name:'Last Orders',desc:'A freezing shockwave damages and slows enemies.',up:()=>`Bigger blast, heavier slow and lower cooldown.`,max:6},
{id:'fan',icon:'🗡️',name:'Blade Fan',desc:'Launches a spread of piercing blades.',up:l=>`${3+Math.min(6,l)} blades with better piercing.`,max:7},
{id:'poison',icon:'☠️',name:'Toxic Trail',desc:'Leaves damaging puddles while moving.',up:()=>`Bigger, stronger and longer-lasting puddles.`,max:6},
{id:'shield',icon:'🛡️',name:'Bouncer Shield',desc:'Reduces damage and periodically blocks a hit.',up:l=>`More protection; block recharges in ${Math.max(3,9-l)}s.`,max:6},
{id:'meteor',icon:'☄️',name:'Barstool Meteor',desc:'Drops explosive barstools into enemy crowds.',up:()=>`Bigger explosions, more damage and faster drops.`,max:7},
{id:'drone',icon:'🤖',name:'Little Kev',desc:'A loyal drone circles Tavi and fires independently.',up:()=>`Faster drone fire with stronger rounds.`,max:6},
{id:'vampire',icon:'🩸',name:'Hair of the Dog',desc:'Kills occasionally restore health.',up:l=>`Higher heal chance and +${l+2} health per proc.`,max:5}
];
const ET={grunt:{r:15,s:72,h:24,d:10,xp:3,c:'#ff687f'},runner:{r:11,s:124,h:16,d:8,xp:3,c:'#ffb56b'},tank:{r:23,s:45,h:72,d:18,xp:7,c:'#b777ff'},splitter:{r:17,s:62,h:44,d:12,xp:6,c:'#66e0b5'},boss:{r:42,s:40,h:540,d:28,xp:45,c:'#ffe26b'}};
let S,last=performance.now(),announceTimer;
function fresh(){return{run:false,paused:true,choosing:false,over:false,t:0,wave:1,waveT:0,waveLen:28,spawnT:0,kills:0,level:1,xp:0,need:12,rerolls:1,pending:0,shake:0,flash:0,p:{x:640,y:360,r:18,s:235,hp:100,max:100,inv:0,powers:new Map([['blaster',1]]),timers:{},shield:true,shieldT:0},enemies:[],shots:[],gems:[],fx:[],puddles:[],nums:[]}}
function plev(id){return S.p.powers.get(id)||0}
function fmt(s){return`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`}
function announce(t){ui.announce.textContent=t;ui.announce.classList.add('show');clearTimeout(announceTimer);announceTimer=setTimeout(()=>ui.announce.classList.remove('show'),1200)}
function reset(){S=fresh();ui.start.classList.remove('open');ui.levelModal.classList.remove('open');ui.over.classList.remove('open');S.run=true;S.paused=false;last=performance.now();announce('WAVE 1');slots();hud()}
function hud(){ui.level.textContent=S.level;ui.wave.textContent=S.wave;ui.kills.textContent=S.kills;ui.time.textContent=fmt(S.t);ui.health.textContent=`${Math.ceil(S.p.hp)} / ${S.p.max}`;ui.healthBar.style.width=`${clamp(S.p.hp/S.p.max*100,0,100)}%`;ui.xp.textContent=`${S.xp} / ${S.need}`;ui.xpBar.style.width=`${clamp(S.xp/S.need*100,0,100)}%`;ui.rerolls.textContent=S.rerolls;ui.pause.textContent=S.paused&&!S.choosing?'Resume':'Pause'}
function slots(){const a=[...S.p.powers];ui.slots.innerHTML='';ui.slotCounter.textContent=`${a.length} / 4`;for(let i=0;i<4;i++){const d=document.createElement('div');d.className='power-slot';if(a[i]){const [id,l]=a[i],p=POWERS.find(x=>x.id===id);d.classList.add('filled');d.innerHTML=`<span class="power-icon">${p.icon}</span><span><strong>${p.name}</strong><small>Level ${l}</small></span>`}else d.textContent='Empty power slot';ui.slots.appendChild(d)}}
function choices(){const canNew=S.p.powers.size<4,pool=POWERS.filter(p=>plev(p.id)<p.max&&(plev(p.id)||canNew)),out=[];while(pool.length&&out.length<4)out.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0]);return out}
function showChoices(){S.choosing=S.paused=true;ui.levelModal.classList.add('open');renderChoices();hud()}
function renderChoices(){ui.choices.innerHTML='';choices().forEach(p=>{const l=plev(p.id),b=document.createElement('button');b.className='power-choice';b.innerHTML=`<span class="choice-icon">${p.icon}</span><h3>${p.name}</h3><p>${l?p.up(l+1):p.desc}</p><span class="choice-level">${l?`Upgrade ${l} → ${l+1}`:'New power'}</span>`;b.onclick=()=>pick(p.id);ui.choices.appendChild(b)});ui.reroll.disabled=S.rerolls<=0}
function pick(id){const old=plev(id);S.p.powers.set(id,old+1);if(id==='shield'){S.p.max+=old?3:8;S.p.hp=Math.min(S.p.max,S.p.hp+10);S.p.shield=true}slots();if(--S.pending>0)renderChoices();else{S.choosing=S.paused=false;ui.levelModal.classList.remove('open');last=performance.now()}hud()}
function gain(n){S.xp+=n;while(S.xp>=S.need){S.xp-=S.need;S.level++;S.need=Math.floor(12+S.level*7+S.level**1.18);S.pending++;if(S.level%4===0)S.rerolls++}if(S.pending&&!S.choosing)showChoices()}
function enemyType(){const r=Math.random();if(S.wave>=4&&r<.12)return'tank';if(S.wave>=3&&r<.26)return'splitter';if(S.wave>=2&&r<.46)return'runner';return'grunt'}
function spawn(type=enemyType(),x=null,y=null,scale=1){const e=ET[type],m=45,side=Math.floor(Math.random()*4);if(x===null){if(side===0){x=rnd(0,1280);y=-m}if(side===1){x=1280+m;y=rnd(0,720)}if(side===2){x=rnd(0,1280);y=720+m}if(side===3){x=-m;y=rnd(0,720)}}const ws=1+(S.wave-1)*.115;S.enemies.push({id:Math.random(),type,x,y,r:e.r*scale,s:e.s*(1+Math.min(.45,S.wave*.012)),hp:e.h*ws*scale,max:e.h*ws*scale,d:e.d*(1+S.wave*.065),xp:Math.round(e.xp*scale),c:e.c,hit:0,slow:0,slowT:0,touch:0,orb:new Map})}
function spawner(dt){S.waveT+=dt;S.spawnT-=dt;if(S.spawnT<=0){for(let i=0;i<1+Math.floor(S.wave/7);i++)spawn();S.spawnT=Math.max(.16,.72-S.wave*.035)}if(S.waveT>=S.waveLen){S.wave++;S.waveT=0;S.waveLen=Math.max(22,28-S.wave*.25);S.p.hp=Math.min(S.p.max,S.p.hp+8);if(S.wave%3===0)S.rerolls++;if(S.wave%5===0){spawn('boss');announce(`BOSS WAVE ${S.wave}`)}else announce(`WAVE ${S.wave}`)}}
function move(dt){let x=0,y=0;if(keys.has('w')||keys.has('arrowup'))y--;if(keys.has('s')||keys.has('arrowdown'))y++;if(keys.has('a')||keys.has('arrowleft'))x--;if(keys.has('d')||keys.has('arrowright'))x++;const l=Math.hypot(x,y)||1,m=x||y;S.p.x=clamp(S.p.x+x/l*S.p.s*dt,S.p.r,1280-S.p.r);S.p.y=clamp(S.p.y+y/l*S.p.s*dt,S.p.r,720-S.p.r);S.p.inv=Math.max(0,S.p.inv-dt);if(plev('shield')&&!S.p.shield&&(S.p.shieldT-=dt)<=0)S.p.shield=true;if(m&&plev('poison')){S.p.timers.poison=(S.p.timers.poison||0)-dt;if(S.p.timers.poison<=0){const n=plev('poison');S.puddles.push({x:S.p.x,y:S.p.y,r:28+n*3,life:2.8+n*.45,d:8+n*5,tick:0});S.p.timers.poison=Math.max(.16,.42-n*.035)}}}
function nearest(from=S.p){let t=null,b=1e9;S.enemies.forEach(e=>{const d=dist(from,e);if(d<b){b=d;t=e}});return t}
function cluster(){let best=null,n=-1;S.enemies.forEach(e=>{const c=S.enemies.filter(o=>dist(e,o)<135).length;if(c>n){n=c;best=e}});return best}
function shot(x,y,a,s,d,c,r=5,pierce=0){S.shots.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,d,c,r,life:2,pierce,hit:new Set})}
function lightning(first,l){const hit=[];let t=first;for(let i=0;i<Math.min(6,l+2)&&t;i++){hit.push(t);hurt(t,12+l*6,'#e2c7ff');const prev=t;t=S.enemies.filter(e=>!hit.includes(e)&&dist(prev,e)<190).sort((a,b)=>dist(prev,a)-dist(prev,b))[0]}S.fx.push({type:'line',pts:[{x:S.p.x,y:S.p.y},...hit.map(e=>({x:e.x,y:e.y}))],life:.16,max:.16})}
function powers(dt){const T=S.p.timers;['blaster','lightning','frost','fan','meteor','drone'].forEach(k=>T[k]=(T[k]||0)-dt);const t=nearest();if(plev('blaster')&&t&&T.blaster<=0){const l=plev('blaster');shot(S.p.x,S.p.y,ang(S.p,t),580,7+l*3.4,'#78d8ff');T.blaster=Math.max(.16,.65-l*.055)}if(plev('lightning')&&t&&T.lightning<=0){const l=plev('lightning');lightning(t,l);T.lightning=Math.max(.8,2.7-l*.24)}if(plev('frost')&&T.frost<=0){const l=plev('frost'),r=125+l*16;S.fx.push({type:'ring',x:S.p.x,y:S.p.y,r:5,maxR:r,life:.48,max:.48,c:'#9ce9ff'});S.enemies.forEach(e=>{if(dist(S.p,e)<=r){hurt(e,10+l*7,'#b8f1ff');e.slow=.35+l*.055;e.slowT=2.2+l*.25}});T.frost=Math.max(2.4,6.2-l*.55)}if(plev('fan')&&t&&T.fan<=0){const l=plev('fan'),n=3+Math.min(6,l),a=ang(S.p,t);for(let i=0;i<n;i++)shot(S.p.x,S.p.y,a+(i-(n-1)/2)*.12,460,8+l*3,'#ff9e80',6,1+Math.floor(l/3));T.fan=Math.max(.72,2.15-l*.17)}if(plev('meteor')&&S.enemies.length&&T.meteor<=0){const l=plev('meteor'),t=cluster();S.fx.push({type:'meteor',x:t.x,y:t.y,r:35+l*4,life:.72,max:.72,l});T.meteor=Math.max(1.8,5.4-l*.42)}if(plev('drone')&&t&&T.drone<=0){const l=plev('drone'),d=drone();shot(d.x,d.y,ang(d,t),650,6+l*4,'#77ffd7',4);T.drone=Math.max(.28,1.05-l*.1)}}
function drone(){const a=S.t*1.8;return{x:S.p.x+Math.cos(a)*58,y:S.p.y+Math.sin(a)*58}}
function enemies(dt){S.enemies.forEach(e=>{e.hit=Math.max(0,e.hit-dt);e.touch=Math.max(0,e.touch-dt);if(e.slowT>0)e.slowT-=dt;else e.slow=0;const a=ang(e,S.p);e.x+=Math.cos(a)*e.s*(1-e.slow)*dt;e.y+=Math.sin(a)*e.s*(1-e.slow)*dt;if(dist(e,S.p)<e.r+S.p.r&&e.touch<=0){hurtPlayer(e.d);e.touch=.7;e.x-=Math.cos(a)*18;e.y-=Math.sin(a)*18}})}
function hurtPlayer(n){if(S.p.inv>0)return;const l=plev('shield');if(l&&S.p.shield){S.p.shield=false;S.p.shieldT=Math.max(3,9-l);S.p.inv=.45;S.fx.push({type:'ring',x:S.p.x,y:S.p.y,r:8,maxR:70,life:.3,max:.3,c:'#ffe4a4'});return}n*=1-(l?Math.min(.42,l*.07):0);S.p.hp-=n;S.p.inv=.55;S.shake=10;S.flash=.17;num(S.p.x,S.p.y-25,`-${Math.ceil(n)}`,'#ff7088',.75);if(S.p.hp<=0)gameOver()}
function hurt(e,n,c='#fff'){e.hp-=n;e.hit=.08;num(e.x,e.y-e.r,Math.round(n),c,.52);if(e.hp<=0)kill(e)}
function kill(e){const i=S.enemies.indexOf(e);if(i<0)return;S.enemies.splice(i,1);S.kills++;S.gems.push({x:e.x,y:e.y,v:e.xp,r:e.type==='boss'?9:5,p:rnd(0,TAU)});S.fx.push({type:'burst',x:e.x,y:e.y,r:e.r,life:.35,max:.35,c:e.c});if(e.type==='splitter'){spawn('runner',e.x+rnd(-12,12),e.y+rnd(-12,12),.75);spawn('runner',e.x+rnd(-12,12),e.y+rnd(-12,12),.75)}const l=plev('vampire');if(l&&Math.random()<.07+l*.035){const h=2+l;S.p.hp=Math.min(S.p.max,S.p.hp+h);num(S.p.x,S.p.y-28,`+${h}`,'#79ff9f',.85)}}
function projectiles(dt){S.shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;S.enemies.forEach(e=>{if(s.life<=0||s.hit.has(e.id))return;if(dist(s,e)<s.r+e.r){s.hit.add(e.id);hurt(e,s.d,s.c);if(s.pierce)s.pierce--;else s.life=0}})});S.shots=S.shots.filter(s=>s.life>0&&s.x>-80&&s.x<1360&&s.y>-80&&s.y<800)}
function orbit(){const l=plev('orbit');if(!l)return;const n=Math.min(6,l+1),r=52+l*4;for(let i=0;i<n;i++){const a=S.t*(1.55+l*.08)+i/n*TAU,o={x:S.p.x+Math.cos(a)*r,y:S.p.y+Math.sin(a)*r,r:10};S.enemies.forEach(e=>{const next=e.orb.get(i)||0;if(S.t>=next&&dist(o,e)<o.r+e.r){hurt(e,6+l*4,'#ffd36b');e.orb.set(i,S.t+.38)}})}}
function puddles(dt){S.puddles.forEach(p=>{p.life-=dt;p.tick-=dt;if(p.tick<=0){S.enemies.slice().forEach(e=>{if(dist(p,e)<p.r+e.r*.4)hurt(e,p.d*.25,'#91ff74')});p.tick=.25}});S.puddles=S.puddles.filter(p=>p.life>0)}
function gems(dt){S.gems.forEach(g=>{g.p+=dt*5;const d=dist(g,S.p);if(d<150){const a=ang(g,S.p),s=120+(150-d)*5;g.x+=Math.cos(a)*s*dt;g.y+=Math.sin(a)*s*dt}if(d<g.r+S.p.r+6){g.got=true;gain(g.v)}});S.gems=S.gems.filter(g=>!g.got)}
function num(x,y,text,c,life){S.nums.push({x,y,text,c,life,max:life})}
function effects(dt){S.fx.forEach(f=>{f.life-=dt;if(f.type==='ring')f.r+=(f.maxR-f.r)*Math.min(1,dt*13);if(f.type==='meteor'&&f.life<=0&&!f.done){f.done=true;const r=70+f.l*9;S.enemies.slice().forEach(e=>{if(dist(f,e)<r+e.r)hurt(e,30+f.l*13,'#ff8a71')});S.fx.push({type:'burst',x:f.x,y:f.y,r,life:.5,max:.5,c:'#ff8a71'});S.shake=14}});S.fx=S.fx.filter(f=>f.life>0||(f.type==='meteor'&&!f.done));S.nums.forEach(n=>{n.life-=dt;n.y-=34*dt});S.nums=S.nums.filter(n=>n.life>0);S.shake=Math.max(0,S.shake-35*dt);S.flash=Math.max(0,S.flash-dt)}
function update(dt){S.t+=dt;spawner(dt);move(dt);powers(dt);enemies(dt);projectiles(dt);orbit();puddles(dt);gems(dt);effects(dt);hud()}
function background(){const g=ctx.createRadialGradient(640,360,40,640,360,900);g.addColorStop(0,'#131d39');g.addColorStop(1,'#070b17');ctx.fillStyle=g;ctx.fillRect(0,0,1280,720);ctx.strokeStyle='rgba(255,255,255,.035)';for(let x=0;x<1280;x+=52){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,720);ctx.stroke()}for(let y=0;y<720;y+=52){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1280,y);ctx.stroke()}ctx.fillStyle=S.wave%5===0?'#ffd36b':'#8dffbd';ctx.fillRect(0,0,1280*S.waveT/S.waveLen,5)}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.shadowBlur=e.type==='boss'?22:10;ctx.shadowColor=e.c;ctx.fillStyle=e.hit?'#fff':e.c;ctx.beginPath();ctx.arc(0,0,e.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(5,8,17,.65)';ctx.beginPath();ctx.arc(-e.r*.3,-e.r*.12,Math.max(2,e.r*.1),0,TAU);ctx.fill();ctx.beginPath();ctx.arc(e.r*.3,-e.r*.12,Math.max(2,e.r*.1),0,TAU);ctx.fill();ctx.restore();if(e.hp<e.max){ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(e.x-e.r,e.y-e.r-10,e.r*2,4);ctx.fillStyle='#8dffbd';ctx.fillRect(e.x-e.r,e.y-e.r-10,e.r*2*clamp(e.hp/e.max,0,1),4)}}
function drawPlayer(){ctx.save();ctx.translate(S.p.x,S.p.y);if(S.p.inv&&Math.floor(S.p.inv*18)%2===0)ctx.globalAlpha=.4;ctx.shadowBlur=22;ctx.shadowColor='#8dffbd';ctx.fillStyle='#8dffbd';ctx.beginPath();ctx.arc(0,0,S.p.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#071018';ctx.beginPath();ctx.arc(-6,-3,2.5,0,TAU);ctx.fill();ctx.beginPath();ctx.arc(6,-3,2.5,0,TAU);ctx.fill();ctx.lineWidth=2.3;ctx.strokeStyle='#071018';ctx.beginPath();ctx.arc(0,2,7,.2,Math.PI-.2);ctx.stroke();ctx.restore();if(plev('shield')&&S.p.shield){ctx.strokeStyle='rgba(255,228,164,.7)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(S.p.x,S.p.y,S.p.r+8+Math.sin(S.t*4)*2,0,TAU);ctx.stroke()}}
function draw(){ctx.save();ctx.translate(S.shake?rnd(-S.shake,S.shake):0,S.shake?rnd(-S.shake,S.shake):0);background();S.puddles.forEach(p=>{ctx.globalAlpha=Math.min(.4,p.life/2);ctx.fillStyle='#6cff72';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,TAU);ctx.fill()});ctx.globalAlpha=1;S.gems.forEach(g=>{ctx.save();ctx.translate(g.x,g.y);ctx.rotate(Math.PI/4);ctx.fillStyle='#72d9ff';ctx.shadowBlur=15;ctx.shadowColor='#63c9ff';const z=g.r+Math.sin(g.p)*1.5;ctx.fillRect(-z,-z,z*2,z*2);ctx.restore()});S.enemies.forEach(drawEnemy);S.shots.forEach(s=>{ctx.fillStyle=s.c;ctx.shadowBlur=11;ctx.shadowColor=s.c;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,TAU);ctx.fill()});ctx.shadowBlur=0;const l=plev('orbit');if(l){const n=Math.min(6,l+1),r=52+l*4;for(let i=0;i<n;i++){const a=S.t*(1.55+l*.08)+i/n*TAU;ctx.fillStyle='#ffd36b';ctx.fillRect(S.p.x+Math.cos(a)*r-8,S.p.y+Math.sin(a)*r-11,16,22)}}if(plev('drone')){const d=drone();ctx.fillStyle='#77ffd7';ctx.beginPath();ctx.arc(d.x,d.y,10,0,TAU);ctx.fill()}drawPlayer();S.fx.forEach(f=>{const a=clamp(f.life/f.max,0,1);ctx.globalAlpha=a;if(f.type==='ring'){ctx.strokeStyle=f.c;ctx.lineWidth=5;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,TAU);ctx.stroke()}if(f.type==='burst'){ctx.globalAlpha=a*.55;ctx.fillStyle=f.c;ctx.beginPath();ctx.arc(f.x,f.y,f.r*(1.3-a*.3),0,TAU);ctx.fill()}if(f.type==='line'){ctx.strokeStyle='#e9d7ff';ctx.lineWidth=4;ctx.beginPath();f.pts.forEach((p,i)=>i?ctx.lineTo(p.x+rnd(-4,4),p.y+rnd(-4,4)):ctx.moveTo(p.x,p.y));ctx.stroke()}if(f.type==='meteor'){const q=1-f.life/f.max;ctx.globalAlpha=.35+q*.45;ctx.strokeStyle='#ff7b78';ctx.lineWidth=4;ctx.beginPath();ctx.arc(f.x,f.y,f.r*(1-q*.35),0,TAU);ctx.stroke()}});ctx.globalAlpha=1;S.nums.forEach(n=>{ctx.globalAlpha=clamp(n.life/.35,0,1);ctx.fillStyle=n.c;ctx.font='bold 16px system-ui';ctx.textAlign='center';ctx.fillText(n.text,n.x,n.y)});ctx.globalAlpha=1;ctx.restore();if(S.flash){ctx.fillStyle=`rgba(255,70,100,${S.flash*.9})`;ctx.fillRect(0,0,1280,720)}if(S.paused&&!S.choosing&&!S.over&&S.run){ctx.fillStyle='rgba(4,7,15,.62)';ctx.fillRect(0,0,1280,720);ctx.fillStyle='#fff';ctx.font='900 58px system-ui';ctx.textAlign='center';ctx.fillText('PAUSED',640,360)}}
function gameOver(){S.over=S.paused=true;ui.results.innerHTML=`<div class="result"><span>Time survived</span><strong>${fmt(S.t)}</strong></div><div class="result"><span>Wave reached</span><strong>${S.wave}</strong></div><div class="result"><span>Enemies flattened</span><strong>${S.kills}</strong></div>`;ui.over.classList.add('open')}
function toggle(){if(!S.run||S.choosing||S.over)return;S.paused=!S.paused;last=performance.now();hud()}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;if(S.run&&!S.paused&&!S.over)update(dt);draw();requestAnimationFrame(loop)}
S=fresh();slots();hud();draw();requestAnimationFrame(loop);
$('startButton').onclick=reset;$('restartButton').onclick=reset;ui.pause.onclick=toggle;ui.reroll.onclick=()=>{if(S.rerolls){S.rerolls--;renderChoices();hud()}};
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k)}if(k==='p'||k==='escape')toggle()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();if(S.run&&!S.choosing&&!S.over){S.paused=true;hud()}});
document.querySelectorAll('#mobileControls button').forEach(b=>{const k=b.dataset.key.toLowerCase(),on=e=>{e.preventDefault();keys.add(k)},off=e=>{e.preventDefault();keys.delete(k)};b.onpointerdown=on;b.onpointerup=off;b.onpointercancel=off;b.onpointerleave=off});
